### ISSUE TITLE
IDA9 not support

### ISSUE THREAD

**Issue by lavender1203** [L4ys/LazyIDA#33]
I'm using IDA9, but it doesn't work

**Comment by n132** [comment]
I have the same issue but I fixed it by
```diff
100c100,103
<             dump_type = idaapi.BWN_HEXVIEW
---
>             try:
>                 dump_type = idaapi.BWN_HEXVIEW
>             except:
>                 dump_type = idaapi.BWN_DUMP
418c421,424
<             dump_type = idaapi.BWN_HEXVIEW
---
>             try:
>                 dump_type = idaapi.BWN_HEXVIEW
>             except:
>                 dump_type = idaapi.BWN_DUMP
```
I have no idea about `idaapi`, but it seems like my `idaapi` doesn't `idaapi.BWN_HEXVIEW`.

I don't know if it's a common problem worth an update. 

@L4ys  Thanks for checking this issue.

**Comment by CNDspace** [comment]
Hi guys! I made a PR with fix from @n132 , hope @L4ys will merge it.

**Comment by L4ys** [comment]
Can you provide more detailed information about the issue, such as how to reproduce it? 
I haven't encountered any problems with IDA Pro 9.0.241217 and 9.1.250226.

**Comment by CNDspace** [comment]
```
LazyIDA (v1.0.0.3) plugin has been loaded.
Traceback (most recent call last):
  File "<ida_path>/plugins/LazyIDA.py", line 100, in update
    dump_type = idaapi.BWN_HEXVIEW
                ^^^^^^^^^^^^^^^^^^
AttributeError: module 'idaapi' has no attribute 'BWN_HEXVIEW'
Traceback (most recent call last):
  File "<ida_path>/plugins/LazyIDA.py", line 100, in update
    dump_type = idaapi.BWN_HEXVIEW
                ^^^^^^^^^^^^^^^^^^
AttributeError: module 'idaapi' has no attribute 'BWN_HEXVIEW'
```

**Comment by L4ys** [comment]
Can you provide the IDA version you're testing? thanks.

**Comment by L4ys** [comment]
OK, I've discovered that the `BWN_HEXVIEW` definition is not in the IDA 9.0 Beta SDK, so it should only affect the Beta version.
this might be the root cause.
For now, I'll merge this fix.
